# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20170928_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cuisine',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
